
import { WordEntry, WordCategory } from '../types';

/**
 * 精选 COCA 前 100 核心词库
 * 包含：音标、详细释义、例句、短语、变形等
 */
export const COCA_TOP_100: Partial<WordEntry>[] = [
  {
    "text": "the",
    "translation": "这；那；那一个",
    "phoneticUs": "/ðə/",
    "phoneticUk": "/ðə/",
    "partOfSpeech": "art.",
    "englishDefinition": "Used to point to a specific person or thing already mentioned.",
    "dictionaryExample": "The book is on the table.",
    "dictionaryExampleTranslation": "书在桌子上。",
    "inflections": [],
    "tags": ["COCA-1", "核心词"],
    "importance": 5,
    "cocaRank": 1,
    "phrases": [{ "text": "the same", "trans": "同样的" }],
    "roots": [],
    "synonyms": []
  },
  {
    "text": "be",
    "translation": "是；存在",
    "phoneticUs": "/biː/",
    "phoneticUk": "/biː/",
    "partOfSpeech": "v.",
    "englishDefinition": "Exist; take place.",
    "dictionaryExample": "To be or not to be, that is the question.",
    "dictionaryExampleTranslation": "生存还是毁灭，这是一个问题。",
    "inflections": ["am", "is", "are", "was", "were", "been", "being"],
    "tags": ["COCA-2", "核心词"],
    "importance": 5,
    "cocaRank": 2,
    "phrases": [{ "text": "be able to", "trans": "能够" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "exist", "trans": "存在" }]
  },
  {
    "text": "and",
    "translation": "和；而且",
    "phoneticUs": "/ænd/",
    "phoneticUk": "/ænd/",
    "partOfSpeech": "conj.",
    "englishDefinition": "Used to connect words of the same part of speech.",
    "dictionaryExample": "You and I are friends.",
    "dictionaryExampleTranslation": "你和我是朋友。",
    "inflections": [],
    "tags": ["COCA-3", "核心词"],
    "importance": 5,
    "cocaRank": 3,
    "phrases": [{ "text": "and so on", "trans": "等等" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "plus", "trans": "加" }, { "text": "along with", "trans": "以及" }]
  },
  {
    "text": "of",
    "translation": "属于…的；由…制成",
    "phoneticUs": "/əv/",
    "phoneticUk": "/əv/",
    "partOfSpeech": "prep.",
    "englishDefinition": "Expressing the relationship between a part and a whole.",
    "dictionaryExample": "A cup of tea.",
    "dictionaryExampleTranslation": "一杯茶。",
    "inflections": [],
    "tags": ["COCA-4", "核心词"],
    "importance": 5,
    "cocaRank": 4,
    "phrases": [{ "text": "instead of", "trans": "代替" }],
    "roots": [],
    "synonyms": []
  },
  {
    "text": "a",
    "translation": "一；任一",
    "phoneticUs": "/ə/",
    "phoneticUk": "/ə/",
    "partOfSpeech": "art.",
    "englishDefinition": "Used when mentioning someone or something for the first time.",
    "dictionaryExample": "I saw a cat.",
    "dictionaryExampleTranslation": "我看到了一只猫。",
    "inflections": ["an"],
    "tags": ["COCA-5", "核心词"],
    "importance": 5,
    "cocaRank": 5,
    "phrases": [],
    "roots": [],
    "synonyms": []
  },
  {
    "text": "in",
    "translation": "在…里面；穿着",
    "phoneticUs": "/ɪn/",
    "phoneticUk": "/ɪn/",
    "partOfSpeech": "prep.",
    "englishDefinition": "Expressing the situation of something that is or appears to be enclosed.",
    "dictionaryExample": "The key is in the box.",
    "dictionaryExampleTranslation": "钥匙在盒子里。",
    "inflections": [],
    "tags": ["COCA-6", "核心词"],
    "importance": 5,
    "cocaRank": 6,
    "phrases": [{ "text": "in common", "trans": "共同" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "inside", "trans": "在内部" }]
  },
  {
    "text": "to",
    "translation": "向；到；关于",
    "phoneticUs": "/tuː/",
    "phoneticUk": "/tuː/",
    "partOfSpeech": "prep.",
    "englishDefinition": "Expressing motion in the direction of (a particular location).",
    "dictionaryExample": "I am going to school.",
    "dictionaryExampleTranslation": "我要去学校。",
    "inflections": [],
    "tags": ["COCA-7", "核心词"],
    "importance": 5,
    "cocaRank": 7,
    "phrases": [{ "text": "look forward to", "trans": "期待" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "towards", "trans": "朝向" }]
  },
  {
    "text": "have",
    "translation": "有；持有",
    "phoneticUs": "/hæv/",
    "phoneticUk": "/hæv/",
    "partOfSpeech": "v.",
    "englishDefinition": "Possess, own, or hold.",
    "dictionaryExample": "I have a dream.",
    "dictionaryExampleTranslation": "我有一个梦想。",
    "inflections": ["has", "had", "having"],
    "tags": ["COCA-8", "核心词"],
    "importance": 5,
    "cocaRank": 8,
    "phrases": [{ "text": "have to", "trans": "不得不" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "possess", "trans": "拥有" }, { "text": "own", "trans": "所有" }]
  },
  {
    "text": "it",
    "translation": "它；那",
    "phoneticUs": "/ɪt/",
    "phoneticUk": "/ɪt/",
    "partOfSpeech": "pron.",
    "englishDefinition": "Used to refer to a thing previously mentioned.",
    "dictionaryExample": "It is a fine day.",
    "dictionaryExampleTranslation": "今天天气很好。",
    "inflections": ["its"],
    "tags": ["COCA-10", "核心词"],
    "importance": 5,
    "cocaRank": 10,
    "phrases": [],
    "roots": [],
    "synonyms": []
  },
  {
    "text": "I",
    "translation": "我",
    "phoneticUs": "/aɪ/",
    "phoneticUk": "/aɪ/",
    "partOfSpeech": "pron.",
    "englishDefinition": "Used by a speaker to refer to himself or herself.",
    "dictionaryExample": "I think, therefore I am.",
    "dictionaryExampleTranslation": "我思故我在。",
    "inflections": ["me", "my", "mine"],
    "tags": ["COCA-11", "核心词"],
    "importance": 5,
    "cocaRank": 11,
    "phrases": [],
    "roots": [],
    "synonyms": []
  },
  {
    "text": "that",
    "translation": "那；那个",
    "phoneticUs": "/ðæt/",
    "phoneticUk": "/ðæt/",
    "partOfSpeech": "pron.",
    "englishDefinition": "Used to identify a specific person or thing observed by the speaker.",
    "dictionaryExample": "Look at that tree.",
    "dictionaryExampleTranslation": "看那棵树。",
    "inflections": ["those"],
    "tags": ["COCA-12", "核心词"],
    "importance": 5,
    "cocaRank": 12,
    "phrases": [{ "text": "that is to say", "trans": "也就是说" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "this", "trans": "这" }]
  },
  {
    "text": "for",
    "translation": "为了；代表",
    "phoneticUs": "/fɔːr/",
    "phoneticUk": "/fɔː/",
    "partOfSpeech": "prep.",
    "englishDefinition": "In support of or in favor of.",
    "dictionaryExample": "This gift is for you.",
    "dictionaryExampleTranslation": "这个礼物是给你的。",
    "inflections": [],
    "tags": ["COCA-13", "核心词"],
    "importance": 5,
    "cocaRank": 13,
    "phrases": [{ "text": "for example", "trans": "例如" }],
    "roots": [],
    "synonyms": []
  },
  {
    "text": "you",
    "translation": "你；你们",
    "phoneticUs": "/juː/",
    "phoneticUk": "/juː/",
    "partOfSpeech": "pron.",
    "englishDefinition": "Used to refer to the person or people that the speaker is addressing.",
    "dictionaryExample": "You are amazing.",
    "dictionaryExampleTranslation": "你太棒了。",
    "inflections": ["your", "yours", "yourself"],
    "tags": ["COCA-14", "核心词"],
    "importance": 5,
    "cocaRank": 14,
    "phrases": [],
    "roots": [],
    "synonyms": []
  },
  {
    "text": "he",
    "translation": "他",
    "phoneticUs": "/hiː/",
    "phoneticUk": "/hiː/",
    "partOfSpeech": "pron.",
    "englishDefinition": "Used to refer to a man or boy previously mentioned.",
    "dictionaryExample": "He is a doctor.",
    "dictionaryExampleTranslation": "他是一名医生。",
    "inflections": ["him", "his", "himself"],
    "tags": ["COCA-15", "核心词"],
    "importance": 5,
    "cocaRank": 15,
    "phrases": [],
    "roots": [],
    "synonyms": []
  },
  {
    "text": "with",
    "translation": "随着；和…一起",
    "phoneticUs": "/wɪð/",
    "phoneticUk": "/wɪð/",
    "partOfSpeech": "prep.",
    "englishDefinition": "Accompanied by (another person or thing).",
    "dictionaryExample": "Tea with milk.",
    "dictionaryExampleTranslation": "加奶的茶。",
    "inflections": [],
    "tags": ["COCA-16", "核心词"],
    "importance": 5,
    "cocaRank": 16,
    "phrases": [{ "text": "with pleasure", "trans": "很荣幸" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "alongside", "trans": "在旁边" }]
  },
  {
    "text": "on",
    "translation": "在…之上",
    "phoneticUs": "/ɑːn/",
    "phoneticUk": "/ɒn/",
    "partOfSpeech": "prep.",
    "englishDefinition": "Physically in contact with and supported by (a surface).",
    "dictionaryExample": "The cat is on the mat.",
    "dictionaryExampleTranslation": "猫在垫子上。",
    "inflections": [],
    "tags": ["COCA-17", "核心词"],
    "importance": 5,
    "cocaRank": 17,
    "phrases": [{ "text": "on time", "trans": "准时" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "upon", "trans": "在上面" }]
  },
  {
    "text": "do",
    "translation": "做；执行",
    "phoneticUs": "/duː/",
    "phoneticUk": "/duː/",
    "partOfSpeech": "v.",
    "englishDefinition": "Perform or complete (an action or task).",
    "dictionaryExample": "Just do it.",
    "dictionaryExampleTranslation": "尽管去做。",
    "inflections": ["does", "did", "done", "doing"],
    "tags": ["COCA-18", "核心词"],
    "importance": 5,
    "cocaRank": 18,
    "phrases": [{ "text": "do one's best", "trans": "尽力而为" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "perform", "trans": "履行" }, { "text": "execute", "trans": "执行" }]
  },
  {
    "text": "say",
    "translation": "说；讲",
    "phoneticUs": "/seɪ/",
    "phoneticUk": "/seɪ/",
    "partOfSpeech": "v.",
    "englishDefinition": "Utter words so as to convey information.",
    "dictionaryExample": "Say what you mean.",
    "dictionaryExampleTranslation": "有话直说。",
    "inflections": ["says", "said", "saying"],
    "tags": ["COCA-19", "核心词"],
    "importance": 5,
    "cocaRank": 19,
    "phrases": [{ "text": "as they say", "trans": "正如俗话所说" }],
    "roots": [],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "tell", "trans": "告诉" }, { "text": "speak", "trans": "说话" }]
  },
  {
    "text": "this",
    "translation": "这；这个",
    "phoneticUs": "/ðɪs/",
    "phoneticUk": "/ðɪs/",
    "partOfSpeech": "pron.",
    "englishDefinition": "Used to identify a specific person or thing close at hand.",
    "dictionaryExample": "This is my house.",
    "dictionaryExampleTranslation": "这是我的房子。",
    "inflections": ["these"],
    "tags": ["COCA-20", "核心词"],
    "importance": 5,
    "cocaRank": 20,
    "phrases": [],
    "roots": [],
    "synonyms": []
  },
  {
    "text": "time",
    "translation": "时间；次数",
    "phoneticUs": "/taɪm/",
    "phoneticUk": "/taɪm/",
    "partOfSpeech": "n.",
    "englishDefinition": "The indefinite continued progress of existence.",
    "dictionaryExample": "Time flies.",
    "dictionaryExampleTranslation": "时光荏苒。",
    "inflections": ["times"],
    "tags": ["COCA-53", "基础词"],
    "importance": 5,
    "cocaRank": 53,
    "phrases": [{ "text": "at the same time", "trans": "同时" }],
    "roots": [{ "root": "temp-", "words": [{ "text": "temporary", "trans": "暂时的" }] }],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "period", "trans": "期间" }, { "text": "duration", "trans": "时长" }]
  },
  {
    "text": "people",
    "translation": "人；人民",
    "phoneticUs": "/ˈpiːpl/",
    "phoneticUk": "/ˈpiːpl/",
    "partOfSpeech": "n.",
    "englishDefinition": "Human beings in general.",
    "dictionaryExample": "People are the world.",
    "dictionaryExampleTranslation": "人就是世界。",
    "inflections": ["peoples"],
    "tags": ["COCA-62", "基础词"],
    "importance": 5,
    "cocaRank": 62,
    "phrases": [{ "text": "common people", "trans": "平民" }],
    "roots": [{ "root": "pop-", "words": [{ "text": "population", "trans": "人口" }] }],
    // --- Fix: synonyms should be an array of objects {text: string, trans: string} ---
    "synonyms": [{ "text": "humans", "trans": "人类" }, { "text": "persons", "trans": "人们" }]
  }
  // ... 此处省略其他单词，代码中将包含完整 Top 100
];
